version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app_rest
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx_rest
        ports:
            - "8089:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_mysql_rest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rest_api
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - app-network
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
